name: Node CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x
          - 14.x
        hapi-version:
          - 18
          - 19
          - 20
        exclude:
          - node-version: 10.x
            hapi-version: 19
          - node-version: 10.x
            hapi-version: 20
    env:
      HAPI_VERSION: ${{ matrix.hapi-version }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install, lint, and test
      run: |
        npm install
        npm run lint
        npm test
  coverage:
    runs-on: ubuntu-latest
    env:
      HAPI_VERSION: 20
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: install and test
      run: |
        npm install
        npm test
    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
